### PR TITLE
Add currencies

### PR DESCRIPTION
**Pull request by AngeloGiacco**
adds currencies

mainly deals with different price formatting

adds test for the new price formatting enhancement

### CODE REVIEW

**Comment by robertt** [comment]
maybe don't call it UKFormat lmao

**Comment by AngeloGiacco** [comment]
why not?

**Comment by robertt** [comment]
Because it's not exactly like it's the UKs standard to put the symbol before the text

**Comment by AngeloGiacco** [comment]
You've misunderstood. It's about the commas

**Comment by robertt** [comment]
Ahhh I'm stupid haha

**Pull request merged**
